# Cancer Mutation Analysis

This project analyzes cancer mutation data to identify patterns in genes and cancer types

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
mutation = pd.read_csv("data_mutations.txt", sep="\t", comment="#",low_memory=False)
sample = pd.read_csv("data_clinical_sample.txt", sep="\t")
patient = pd.read_csv("data_clinical_patient.txt", sep="\t")

In [3]:
mutation.head()

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Classification,...,ENSP,ExAC_AF,CENTERS,CCDS,EXON,ExAC_AF_OTH,SAS_MAF,Exon_Number,MINIMISED,PUBMED
0,TBX15,6913,genome.wustl.edu,GRCh37,1,119469161,119469161,+,missense_variant,Missense_Mutation,...,ENSP00000358437,NaN,.,NaN,3/8,NaN,G:0,3/8,1,NaN
1,TCHHL1,126637,genome.wustl.edu,GRCh37,1,152057522,152057522,+,missense_variant,Missense_Mutation,...,ENSP00000357796,NaN,.,CCDS30857.1,3/3,NaN,NaN,3/3,1,NaN
2,DNMT3A,1788,genome.wustl.edu,GRCh37,2,25457243,25457243,+,missense_variant,Missense_Mutation,...,ENSP00000264709,NaN,.,CCDS33157.1,23/23,NaN,NaN,23/23,1,NaN
3,IDH1,3417,genome.wustl.edu,GRCh37,2,209113112,209113112,+,missense_variant,Missense_Mutation,...,ENSP00000260985,NaN,.,CCDS2381.1,4/10,NaN,NaN,4/10,1,NaN
4,GRM7,2917,genome.wustl.edu,GRCh37,3,7503316,7503316,+,synonymous_variant,Silent,...,ENSP00000350348,NaN,.,CCDS43042.1,7/10,NaN,NaN,7/10,1,NaN

In [6]:
sample.head()

,#Patient Identifier,Sample Identifier,Oncotree Code,Cancer Type,Cancer Type Detailed,Tumor Type,Neoplasm Histologic Grade,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site Code,Tumor Disease Anatomic Site,Aneuploidy Score,Sample Type,MSI MANTIS Score,MSIsensor Score,Somatic Status,TMB (nonsynonymous),Tissue Source Site,Tumor Break Load
0,#Identifier to uniquely specify a patient.,A unique sample identifier.,Oncotree Code,Cancer Type,Cancer Type Detailed,Tumor Type,Numeric value to express the degree of abnorma...,Tissue prospective collection indicator.,Tissue retrospective collection indicator.,Tissue Source Site Code,Text term that describes the anatomic site of ...,Aneuploidy Score,"The type of sample (i.e., normal, primary, met...",MSI Score reported by MANTIS. The suggested th...,MSI Score reported by MSIsensor. The suggested...,Somatic Status,TMB (nonsynonymous),"A Tissue Source Site collects samples (tissue,...",The sum of unbalanced somatic chromosomal brea...
1,#STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,NUMBER,STRING,NUMBER,NUMBER,STRING,NUMBER,STRING,NUMBER
2,#1,1,1,1,1,1,1,1,1,1,1,1,9,9,9,1,1,1,1
3,PATIENT_ID,SAMPLE_ID,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,TUMOR_TYPE,GRADE,TISSUE_PROSPECTIVE_COLLECTION_INDICATOR,TISSUE_RETROSPECTIVE_COLLECTION_INDICATOR,TISSUE_SOURCE_SITE_CODE,TUMOR_TISSUE_SITE,ANEUPLOIDY_SCORE,SAMPLE_TYPE,MSI_SCORE_MANTIS,MSI_SENSOR_SCORE,SOMATIC_STATUS,TMB_NONSYNONYMOUS,TISSUE_SOURCE_SITE,TBL_SCORE
4,TCGA-AB-2989,TCGA-AB-2989-03,AML,Leukemia,Acute Myeloid Leukemia,Acute Myeloid Leukemia,NaN,NaN,NaN,AB,NaN,NaN,Primary,NaN,NaN,Matched,0.366666667,Washington University,4

In [7]:
patient.head()

,#Patient Identifier,Subtype,TCGA PanCanAtlas Cancer Type Acronym,Other Patient ID,Diagnosis Age,Sex,Neoplasm Disease Stage American Joint Committee on Cancer Code,American Joint Committee on Cancer Publication Version Type,Last Communication Contact from Initial Pathologic Diagnosis Date,Birth from Initial Pathologic Diagnosis Date,...,Patient Weight,In PanCan Pathway Analysis,Overall Survival Status,Overall Survival (Months),Disease-specific Survival status,Months of disease-specific survival,Disease Free Status,Disease Free (Months),Progression Free Status,Progress Free Survival (Months)
0,#Identifier to uniquely specify a patient.,Subtype,Text field to hold cancer type acronym used by...,Legacy DMP patient identifier (DMPnnnn),Age at which a condition or disease was first ...,Sex,"The extent of a cancer, especially whether the...",The version or edition of the American Joint C...,Time interval from the date of last followup t...,Time interval from a person's date of birth to...,...,Weight measured in kilograms.,Patient Part of PanCan Pathway Analysis,Overall patient survival status.,Overall survival in months since initial diago...,The time period usually begins at the time of ...,The time period (months) usually begins at the...,Disease free status since initial treatment.,Disease free (months) since initial treatment.,Progression Free Status,Progress Free Survival (Months)
1,#STRING,STRING,STRING,STRING,NUMBER,STRING,STRING,STRING,NUMBER,NUMBER,...,NUMBER,STRING,STRING,NUMBER,STRING,NUMBER,STRING,NUMBER,STRING,NUMBER
2,#1,1,1,1,1,1,1,1,1,1,...,1,1,9,1,1,1,1,1,1,1
3,PATIENT_ID,SUBTYPE,CANCER_TYPE_ACRONYM,OTHER_PATIENT_ID,AGE,SEX,AJCC_PATHOLOGIC_TUMOR_STAGE,AJCC_STAGING_EDITION,DAYS_LAST_FOLLOWUP,DAYS_TO_BIRTH,...,WEIGHT,IN_PANCANPATHWAYS_FREEZE,OS_STATUS,OS_MONTHS,DSS_STATUS,DSS_MONTHS,DFS_STATUS,DFS_MONTHS,PFS_STATUS,PFS_MONTHS
4,TCGA-AB-2989,NaN,LAML,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,No,1:DECEASED,11.9998685,NaN,NaN,NaN,NaN,NaN,NaN

  Cleaning