In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [3]:
# Data collection

df = pd.read_csv('fake_real_news_dataset.csv')

In [4]:
df

,article_id,title,content,author,source_credibility_score,num_citations,sentiment_score,clickbait_score,readability_score,label
0,1,tgdc xckafnafq klhwtekh yiccw gbldxchq jebruzw...,aigfywirkx ddtotlp fzncbc erpkpmgoy srngqclly ...,unknown_source,0.56,15,-0.51,0.26,70.63,real
1,2,glsgixcdj sbkok vkuya omyhkxvntu mhmkr kemdqak...,tbyf uqty vqgmc mgjpz cvzcairyk fpvgshruu ujlj...,staff_writer,0.15,2,-0.60,0.69,59.33,fake
2,3,oozhzrh wuzxtvxu pjqqr trdcqbuaj chted wjnhexy...,rpvycgawo fbvxhkdy zdgnkj sopsxrvqy ajlywc jxq...,staff_writer,0.83,6,0.07,0.12,72.34,real
3,4,froluunkef dgqwocvw celnvc vxykk gzjayv idaxmv...,vmnq gdlpgkrc bnnzok bkjtjbg qutiboveu zmedsya...,unknown_source,0.49,1,-0.42,0.64,68.57,fake
4,5,rtfvhoh qpgr fgcimrdz kywmf iqxcon waxkvyavu y...,mfcelget hrfpqklikc myajl yhsaqs rmer urqyjfym...,staff_writer,0.16,3,-0.02,0.68,77.65,fake
...,...,...,...,...,...,...,...,...,...,...
995,996,extdfxdogs jiywaybrok sesuuzjw dxpixcjuf tmlko...,xigokvuybx fcmi wybc ihrj oalocalt nnis cpukaw...,verified_journalist,0.31,0,-0.38,0.68,68.98,fake
996,997,mhmwkwnopw qjncecsum zkjysoq hjvorugm grjq ueu...,fcikyo aggln pzhewbprv rulz pthsrnmvh dhsmma o...,unknown_source,0.42,5,0.58,0.66,59.02,fake
997,998,geno tcjrekas gxswvebwoa alxlzgq gofnvk ybkf j...,sndawxf oufl qghkcvjntk dptmzoq slkrujraet qnk...,verified_journalist,0.68,3,0.26,0.27,57.16,real
998,999,ghcmm cejymxqehk qjuz ntdjnjyg exdlyafllp splm...,nokuid gwrde tenaa vesv uadwwvdzoy iiafhxs nec...,unknown_source,0.84,7,-0.24,0.39,45.79,real
999,1000,riuok wvsgo pygb dcntzgmq jruyztb sleydzmbrg u...,cpavdlo piglmxyc qsigiteu ratqphnisk nggrrzpl ...,unknown_source,0.03,1,0.78,0.73,74.47,fake

In [6]:
df.shape

(1000, 10)

In [7]:
df.dtypes

article_id                    int64
title                           str
content                         str
author                          str
source_credibility_score    float64
num_citations                 int64
sentiment_score             float64
clickbait_score             float64
readability_score           float64
label                           str
dtype: object

In [8]:
df.head()

,article_id,title,content,author,source_credibility_score,num_citations,sentiment_score,clickbait_score,readability_score,label
0,1,tgdc xckafnafq klhwtekh yiccw gbldxchq jebruzw...,aigfywirkx ddtotlp fzncbc erpkpmgoy srngqclly ...,unknown_source,0.56,15,-0.51,0.26,70.63,real
1,2,glsgixcdj sbkok vkuya omyhkxvntu mhmkr kemdqak...,tbyf uqty vqgmc mgjpz cvzcairyk fpvgshruu ujlj...,staff_writer,0.15,2,-0.60,0.69,59.33,fake
2,3,oozhzrh wuzxtvxu pjqqr trdcqbuaj chted wjnhexy...,rpvycgawo fbvxhkdy zdgnkj sopsxrvqy ajlywc jxq...,staff_writer,0.83,6,0.07,0.12,72.34,real
3,4,froluunkef dgqwocvw celnvc vxykk gzjayv idaxmv...,vmnq gdlpgkrc bnnzok bkjtjbg qutiboveu zmedsya...,unknown_source,0.49,1,-0.42,0.64,68.57,fake
4,5,rtfvhoh qpgr fgcimrdz kywmf iqxcon waxkvyavu y...,mfcelget hrfpqklikc myajl yhsaqs rmer urqyjfym...,staff_writer,0.16,3,-0.02,0.68,77.65,fake

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   article_id                1000 non-null   int64
 1   title                     1000 non-null   str
 2   content                   1000 non-null   str
 3   author                    1000 non-null   str
 4   source_credibility_score  1000 non-null   float64
 5   num_citations             1000 non-null   int64
 6   sentiment_score           1000 non-null   float64
 7   clickbait_score           1000 non-null   float64
 8   readability_score         1000 non-null   float64
 9   label                     1000 non-null   str
dtypes: float64(4), int64(2), str(4)
memory usage: 547.5 KB

In [10]:
df.describe()

,article_id,source_credibility_score,num_citations,sentiment_score,clickbait_score,readability_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,0.450920,5.940000,0.057630,0.481570,60.584420
std,288.819436,0.251114,4.583384,0.581706,0.306351,11.417862
min,1.000000,0.000000,0.000000,-1.000000,0.000000,40.040000
25%,250.750000,0.260000,2.750000,-0.450000,0.200000,51.400000
50%,500.500000,0.430000,5.000000,0.100000,0.520000,59.900000
75%,750.250000,0.600000,10.000000,0.552500,0.770000,70.540000
max,1000.000000,1.000000,15.000000,1.000000,1.000000,80.000000

In [11]:
df.columns

Index(['article_id', 'title', 'content', 'author', 'source_credibility_score',
       'num_citations', 'sentiment_score', 'clickbait_score',
       'readability_score', 'label'],
      dtype='str')

In [12]:
df.nunique()

article_id                  1000
title                       1000
content                     1000
author                         3
source_credibility_score     101
num_citations                 16
sentiment_score              198
clickbait_score               92
readability_score            895
label                          2
dtype: int64

In [17]:
df['author'].value_counts()

author
staff_writer           340
unknown_source         332
verified_journalist    328
Name: count, dtype: int64

In [19]:
df.sample(5)        # random 5 rows

,article_id,title,content,author,source_credibility_score,num_citations,sentiment_score,clickbait_score,readability_score,label
232,233,ettj cawo royuyq yvjjele lxzaxw nnsypaxkrl hnb...,qgshvisueo ejdf tjmch xtoc rtodhn lxhweiui qbt...,unknown_source,0.23,8,-0.06,0.25,77.59,real
513,514,dobzvylegj gujxuyqf bhszuxyzox sofftbuf wluvbp...,gtkl wkierx aolfqut cebjzf teulupnrqs ouqljtqf...,unknown_source,0.59,4,0.99,0.06,42.72,real
560,561,mfvuydxdy nfgfipjdr mchdex plvo atibbnf rrksoc...,hummgl euzeditcuh iknfe mwgc sabkxjac lukz frp...,staff_writer,0.52,3,0.31,0.80,59.13,fake
793,794,asna nkkqtmq cjzsc xykubsdp yubxipv qlcqqxzda ...,sjijhijvyq vategl ylodhkeo nilpqo pzgjefk xlbu...,verified_journalist,0.78,15,-0.76,0.04,74.69,real
885,886,cnue ulrajicdi gzaltuaivz evafgftzed xhnaevw s...,kjvybgbe gtyqf ulvc fqdwzei yvxjwhsnqz npmemf ...,staff_writer,0.29,11,0.15,0.04,58.81,real